### ISSUE TITLE
Add Community Partner Section

### ISSUE THREAD

**Issue by rajuljha** [zhcet-code-oasis/code-oasis-website#28]
**We recently joined forces with GDSC-ZHCET to collaborate on projects and events.**
## Tasks: (Tentative)
- [ ] Add community partner section on the website and add a link to it in the navbar.
- [ ] Create a card for each community partner.
- [ ] Each card should have a name, organisation link, and short summary of the organisation (50 words max.)
- [ ] Add socials to the organisation.

### If anyone has any other ideas, feel free to share.
**Let's continue the conversation below**
